### ISSUE TITLE
branch: gh-pages

### ISSUE THREAD

**Issue by akarsh** [Swift-Dev-Ninjas/swift-dev-ninjas.github.io#5]
The following things have been worked on in the branch gh-pages
- [x] Add a getting-started-help.md
This page will help pull request reviewers and contributors to the repository in setting up the environment for the project.
- [X] Add CONTRIBUTING.md
This page will help contributors to the repository to know the style guide followed and the license of the repository.
- [x] Update README.md
Update the readme file by adding two sections and their links,
a. Contributing
b. Code of conduct
Also, a quick intro and link to the getting-started-help document
- [x] Setup the project
To build a website the popular community-driven framework for swift is vapor. I would like to setup the project using the framework vapor.
- [x] Test the project by creating a basic introduction page
Introduction page is created to test the project.
- [x] Remove unused packages and files from the repository
The packages that are not used by the project are being removed. Since only one package is used as template in creating the introduction page. I removed the rest of the boiler plate code from the repository.
- [x] Deploy the project
I tried to rename the project in order to use GitHub pages. But I did not realise that the vapor framework does not generate HTML files. So I tested and deployed on vapor cloud in order to see the project running.

**Comment by brototyp** [comment]
Looks like everything got settled.
